import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import Navigation from "./components/navigation";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} h-screen overflow-hidden`}>
          <Header />

          <main className="relative flex flex-col items-center min-h-screen pt-16 md:pt-24">
            <SignedOut>
              <SignIn routing="hash" />
            </SignedOut>

            <SignedIn>
              <div className="flex-grow w-full max-w-md mx-auto">
                {children}
              </div>
              <Navigation />
            </SignedIn>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
